pub const TILE_PIXELS: u32 = 16;
pub const MAP_WIDTH_TILES: u32 = 80;
pub const MAP_HEIGHT_TILES: u32 = 45;

pub const MAP_WDITH_PIXELS: u32 = TILE_PIXELS * MAP_WIDTH_TILES;
pub const MAP_HEIGHT_PIXELS: u32 = TILE_PIXELS * MAP_HEIGHT_TILES;
